# Assignment 3

## Task 1

1. 
 
Write a function to compute 5/0 and use try/except to catch the exceptions.

In [5]:
def divide(a,b):
    try:
        print(a/b)
    except:
        print('exception occured')


divide(int(input('a=')),int(input('b=')))

a=5
b=0
exception occured


2. 
 
Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"]. 
 
Hint: Subject,Verb and Object should be declared in the program as shown below. 
 
subjects=["Americans ","Indians"] 
verbs=["play","watch"] 
objects=["Baseball","Cricket"] 
 
Output should come as below: 
 
Americans  play Baseball. Americans  play Cricket. Americans  watch Baseball. Americans  watch Cricket. Indians play Baseball. Indians play Cricket. Indians watch Baseball. Indians watch Cricket. 

In [8]:
subjects=["Americans ","Indians"] 
verbs=["play","watch"] 
objects=["Baseball","Cricket"]

sent=[x+' '+y+' '+z for x in subjects for y in verbs for z in objects]

for line in sent:
    print(line)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


## Task 2

1.  
 
Write a function so that the columns of the output matrix are powers of the input vector.  
The order of the powers is determined by the increasing boolean argument. Specifically, when              increasing is False, the i-th output column is the input vector raised element-wise to the power                of N - i - 1.  
 
HINT: Such a matrix with a geometric progression in each row is named for Alexandre               Theophile Vandermonde

In [9]:
import numpy as np

In [42]:
np.vander([1,2,3,4],4)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [41]:
np.vander([1,2,3,4],4,True)

array([[ 1,  1,  1,  1],
       [ 1,  2,  4,  8],
       [ 1,  3,  9, 27],
       [ 1,  4, 16, 64]])

## using List comprehension

In [22]:
v=[1,2,3,4]
inc=True
N=4

In [62]:
def listVander(vec,power,inc=False):
    if inc:
        return [[a**n for n in range(power)] for a in vec]
    else:
        return [[a**n for n in range(N-1,-1,-1)] for a in vec]
    

In [56]:
listVander(v,N)

[[1, 1, 1, 1], [8, 4, 2, 1], [27, 9, 3, 1], [64, 16, 4, 1]]

In [64]:
listVander(v,N,inc)

[[1, 1, 1, 1], [1, 2, 4, 8], [1, 3, 9, 27], [1, 4, 16, 64]]

# Using Numpy

In [65]:
def numPyVander(vec,power,inc=False):
    if inc:
        return np.array([[a**n for n in range(power)] for a in vec])
    else:
        return np.array([[a**n for n in range(N-1,-1,-1)] for a in vec])

In [67]:
numPyVander(v,N)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [69]:
numPyVander(v,N,inc)

array([[ 1,  1,  1,  1],
       [ 1,  2,  4,  8],
       [ 1,  3,  9, 27],
       [ 1,  4, 16, 64]])